# Generated by Django 5.1.6 on 2025-11-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('reserve', 'Reserve'), ('release', 'Release'), ('deallocate', 'Deallocate'), ('ship', 'Ship'), ('adjust', 'Adjust')], max_length=16),
        ),
    ]
