# Generated by Django 5.1.6 on 2025-11-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
    ]
