# Generated by Django 5.1.6 on 2025-11-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_shipment_carrier_shipment_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.00, max_digits=12, help_text='Unit price for inventory valuation'),
        ),
    ]
